language: go

matrix:
  include:
    - go: 1.10.x
      install:
        - go get github.com/gojuno/generator
        - go get golang.org/x/tools/go/loader
    - go: 1.11.x

env:
  - GO111MODULE=on

script:
  - cd $TRAVIS_BUILD_DIR && go run main.go -i github.com/gojuno/metricsgen/tests.Example -o ./tests/
